stages:
  - build
  - process

.build:
  stage: build
  image: mathcomp/mathcomp:${CI_JOB_NAME}
  script:
    - ./create_makefile.sh --without-classic
    - make -j ${NJOBS}

.build-classic:
  stage: build
  image: mathcomp/mathcomp:1.9.0-coq-8.10
  script:
    - ./create_makefile.sh --only-classic
    - make -j ${NJOBS}

.collect-vo-files: 
  # Keep track of all compiled output and the build infrastructure
  artifacts:
    name: prosa-build-files
    paths:
    - Makefile
    - Makefile.conf
    # Ugly hack around https://gitlab.com/gitlab-org/gitlab-runner/issues/2620
    - "*/*.vo"
    - "*/*/*.vo"
    - "*/*/*/*.vo"
    - "*/*/*/*/*.vo"
    - "*/*/*/*/*/*.vo"
    - "*/*/*/*/*/*/*.vo"
    - "*/*/*/*/*/*/*/*.vo"
    - "*/*/*/*/*/*/*/*/*.vo"
    - "*/*/*/*/*/*/*/*/*/*.vo"
    - "*/*.glob"
    - "*/*/*.glob"
    - "*/*/*/*.glob"
    - "*/*/*/*/*.glob"
    - "*/*/*/*/*/*.glob"
    - "*/*/*/*/*/*/*.glob"
    - "*/*/*/*/*/*/*/*.glob"
    - "*/*/*/*/*/*/*/*/*.glob"
    - "*/*/*/*/*/*/*/*/*/*.glob"
    expire_in: 1 week

1.9.0-coq-8.10:
  extends:
    - .build
    - .collect-vo-files

1.9.0-coq-8.10-classic:
  extends:
    - .build-classic
    - .collect-vo-files

proof-length:
  stage: build
  image: python:3-alpine
  script:
    - scripts/proofloc.py --check --long-proofs scripts/known-long-proofs.json `find . -iname *.v`

spell-check:
  stage: build
  image: bbbrandenburg/aspell-ci
  script:
    - scripts/flag-typos-in-comments.sh `find .  -iname '*.v' ! -path './classic/*'`

1.9.0-coq-8.9:
  extends: .build

1.9.0-coq-dev:
  extends:
    - .build
  # it's ok to fail with an unreleased version of Coq
  allow_failure: true

latest-coq-8.10:
  extends:
    - .build
  # it's ok to fail with an unreleased version of ssreflect
  allow_failure: true

validate:
  stage: process
  image: mathcomp/mathcomp:1.9.0-coq-8.10
  needs: ["1.9.0-coq-8.10"]
  dependencies:
    - 1.9.0-coq-8.10
  script: make validate

validate-classic:
  stage: process
  image: mathcomp/mathcomp:1.9.0-coq-8.10
  needs: ["1.9.0-coq-8.10-classic"]
  dependencies:
    - 1.9.0-coq-8.10-classic
  script: make validate

.doc: 
  stage: process
  image: mathcomp/mathcomp:1.9.0-coq-8.10
  script:
    - make html -j ${NJOBS}
    - mv html with-proofs
    - make gallinahtml -j ${NJOBS}
    - mv html without-proofs
    - make htmlpretty -j ${NJOBS}
    - mv html pretty

doc:
  extends:
    - .doc
  needs: ["1.9.0-coq-8.10"]  
  dependencies:
    - 1.9.0-coq-8.10
  artifacts:
    name: "prosa-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

doc-classic:
  extends:
    - .doc
  needs: ["1.9.0-coq-8.10-classic"]  
  dependencies:
    - 1.9.0-coq-8.10-classic
  artifacts:
    name: "prosa-classic-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

proof-state:
  stage: process
  image: mathcomp/mathcomp:1.9.0-coq-8.10
  needs: ["1.9.0-coq-8.10"]  
  dependencies:
    - 1.9.0-coq-8.10
  script:
    - find restructuring util -iname *.v | xargs -P ${NJOBS} -n 1 scripts/record-proof-state.py -c '-R . rt -w -notation-overriden,-parsing' --timeout 20
    - scripts/intersperse-proof-state.py `find restructuring util -iname *.v`
    - cd with-proof-state/
    - ln -s ../scripts/
    - ln -s ../_CoqProject
    - ../create_makefile.sh
    - make -j ${NJOBS}
    - make html -j ${NJOBS} COQDOCEXTRAFLAGS=--plain-comments
    - mv html ../with-proofs-and-proof-state
  artifacts:
    name: "prosa-proof-state-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs-and-proof-state/"
    expire_in: 1 week
