###################### Global Config ######################

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build

###################### Rules and Scripts ##################

.not_in_wip_branches:
  rules:
    - if: ($CI_COMMIT_BRANCH !~ /^wip-.*$/) || ($CI_PIPELINE_SOURCE == "merge_request_event")

.only_in_wip_branches:
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^wip-.*$/) && ($CI_PIPELINE_SOURCE != "merge_request_event")

.build-common:
  stage: build
  script:
    - opam update -y
    - opam remove -y coq-mathcomp-character coq-mathcomp-field coq-mathcomp-solvable  # Check coq-mathcomp-ssreflect is enough
    - opam pin add -n -y -k path coq-prosa .
    - opam install -y -v -j ${NJOBS} coq-prosa

.preferred-stable-version:
    image: mathcomp/mathcomp:1.15.0-coq-8.16

.build:
  image: mathcomp/mathcomp:${CI_JOB_NAME}
  extends: .build-common

.build-dev:
  image: mathcomp/mathcomp-dev:${CI_JOB_NAME}
  extends: .build-common

.install-dependencies:
  script:
   - opam update
   - opam install -y -v -j ${NJOBS} coq-mathcomp-zify coq-coqeal

.make-html:
  script:
    - make html -j ${NJOBS}
    - mv html with-proofs
    - make gallinahtml -j ${NJOBS}
    - mv html without-proofs
    - make htmlpretty -j ${NJOBS}
    - mv html pretty    

###################### The Jobs ######################

1.13.0-coq-8.14:
  extends:
    - .build
    - .not_in_wip_branches

1.14.0-coq-8.15:
  extends:
    - .build
    - .not_in_wip_branches

1.15.0-coq-8.15:
  extends:
    - .build
    - .not_in_wip_branches

compile-and-doc:
  stage: build
  extends:
    - .only_in_wip_branches
    - .preferred-stable-version
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh
    - make -j ${NJOBS}
    - !reference [.make-html, script]
  artifacts:
    name: "prosa-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

compile-and-doc-and-validate:
  stage: build
  extends:
    - .not_in_wip_branches
    - .preferred-stable-version
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh
    - make -j ${NJOBS}
    - !reference [.make-html, script]
    - make validate 2>&1 | tee validation-results.txt
    - scripts/check-validation-output.sh validation-results.txt
  artifacts:
    name: "prosa-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

proof-length:
  stage: build
  image: python:3-alpine
  script:
    - scripts/proofloc.py --check --long-proofs scripts/known-long-proofs.json `find . -iname *.v`

