# Taken from https://gitlab.com/erikmd/docker-coq-gitlab-ci-demo-1/blob/master/.gitlab-ci.yml

stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam update -y
    # NOTE: we currently fix the mathcomp version to 1.8.0 here because
    #       version 1.9.0 causes a build failure that still needs to be
    #       investigated.
    - opam install -y -j ${NJOBS} coq-mathcomp-ssreflect.1.8.0
    - opam config list
    - opam repo list
    - opam list
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - ./create_makefile.sh
    - make -j ${NJOBS}
    - make validate

coq:8.9:
  extends: .build

# Currently does not work with fixed ssreflect version
#coq:dev:
#  extends: .build
