###################### Global Config ######################

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build

###################### Rules and Scripts ##################

.not_in_wip_branches:
  rules:
    - if: ($CI_COMMIT_BRANCH !~ /^wip-.*$/) || ($CI_PIPELINE_SOURCE == "merge_request_event")

.only_in_wip_branches:
  rules:
    - if: ($CI_COMMIT_BRANCH =~ /^wip-.*$/) && ($CI_PIPELINE_SOURCE != "merge_request_event")

.build-common:
  stage: build
  script:
    - opam update -y
    - opam remove -y coq-mathcomp-character coq-mathcomp-field coq-mathcomp-solvable  # Check coq-mathcomp-ssreflect is enough
    - opam pin add -n -y -k path coq-prosa .
    - opam install -y -v -j ${NJOBS} coq-prosa

.preferred-stable-version:
    image: mathcomp/mathcomp:1.15.0-coq-8.16

.build:
  image: mathcomp/mathcomp:${CI_JOB_NAME}
  extends: .build-common

.build-dev:
  image: mathcomp/mathcomp-dev:${CI_JOB_NAME}
  extends: .build-common

.install-dependencies:
  script:
   - opam update
   - opam install -y -v -j ${NJOBS} coq-mathcomp-zify coq-coqeal

.make-html:
  script:
    - make html -j ${NJOBS}
    - mv html with-proofs
    - make gallinahtml -j ${NJOBS}
    - mv html without-proofs
    - make htmlpretty -j ${NJOBS}
    - mv html pretty    

###################### The Jobs ######################

1.13.0-coq-8.14:
  extends:
    - .build
    - .not_in_wip_branches

1.14.0-coq-8.15:
  extends:
    - .build
    - .not_in_wip_branches

1.15.0-coq-8.15:
  extends:
    - .build
    - .not_in_wip_branches

compile-and-doc:
  stage: build
  extends:
    - .only_in_wip_branches
    - .preferred-stable-version
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh --without-classic
    - make -j ${NJOBS}
    - !reference [.make-html, script]
  artifacts:
    name: "prosa-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

compile-and-doc-and-validate:
  stage: build
  extends:
    - .not_in_wip_branches
    - .preferred-stable-version
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh --without-classic
    - make -j ${NJOBS}
    - !reference [.make-html, script]
    - make validate 2>&1 | tee validation-results.txt
    - scripts/check-validation-output.sh --accept-proof-irrelevance validation-results.txt
  artifacts:
    name: "prosa-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

# Check that proof irrelevance shows up only due to refinements.
compile-and-validate:
  stage: build
  extends:
    - .not_in_wip_branches
    - .preferred-stable-version
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh --without-classic --without-refinements
    - make -j ${NJOBS}    
    - make validate 2>&1 | tee validation-results.txt
    - scripts/check-validation-output.sh validation-results.txt

classic-compile-and-doc-and-validate:
  stage: build
  extends:
    - .preferred-stable-version
    - .not_in_wip_branches
  script:
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh --only-classic
    - make -j ${NJOBS}
    - !reference [.make-html, script]
    - make validate
  artifacts:
    name: "prosa-classic-spec-$CI_COMMIT_REF_NAME"
    paths:
      - "with-proofs/"
      - "without-proofs/"
      - "pretty/"
    expire_in: 1 week

proof-length:
  stage: build
  image: python:3-alpine
  script:
    - scripts/proofloc.py --check --long-proofs scripts/known-long-proofs.json `find . -iname *.v`

spell-check:
  extends:  
    - .not_in_wip_branches  
  stage: build
  image: bbbrandenburg/aspell-ci
  script:
    - scripts/flag-typos-in-comments.sh `find .  -iname '*.v' ! -path './classic/*'`

# mathcomp-dev with stable Coq
#coq-8.15:
#  extends:
#    - .build-dev
#    - .not_in_wip_branches    
#  # it's ok to fail with an unreleased version of ssreflect
#  allow_failure: true

# mathcomp-dev with coq-dev
#coq-dev:
#  extends:
#    - .build-dev
#    - .not_in_wip_branches    
#  # it's ok to fail with an unreleased version of ssreflect and Coq
#  allow_failure: true

proof-state:
  extends:
   - .not_in_wip_branches  
  stage: build
  image: bbbrandenburg/alectryon-ci:1.14.0-coq-8.15.0
  script:
    - eval $(opam env "--switch=${COMPILER_EDGE}" --set-switch)
    - !reference [.install-dependencies, script]
    - ./create_makefile.sh --without-classic
    - make -j ${NJOBS} alectryon
  artifacts:
    name: "prosa-proof-state-$CI_COMMIT_REF_NAME"
    paths:
      - "html-alectryon/"
    expire_in: 1 week
