# Taken from https://gitlab.com/erikmd/docker-coq-gitlab-ci-demo-1/blob/master/.gitlab-ci.yml

.build:
  stage: build
  image: mathcomp/mathcomp:${CI_JOB_NAME}
  script:
    - ./create_makefile.sh
    - make -j ${NJOBS}
    - make validate

1.8.0-coq-8.8:
  extends: .build

1.9.0-coq-8.9:
  extends: .build

1.9.0-coq-dev:
  extends: .build
  # it's ok to fail with an unreleased version of Coq
  allow_failure: true 
